<?php

namespace ContainerSdx40xJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisClientsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AvisClientsController' shared autowired service.
     *
     * @return \App\Controller\AvisClientsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AvisClientsController.php';

        $container->services['App\\Controller\\AvisClientsController'] = $instance = new \App\Controller\AvisClientsController();

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\AvisClientsController', $container));

        return $instance;
    }
}
