<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSdx40xJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSdx40xJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSdx40xJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSdx40xJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSdx40xJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sdx40xJ',
    'container.build_id' => 'afd0dc71',
    'container.build_time' => 1658236264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSdx40xJ');
