<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.ad8a04c6.js',
                '/build/app.cab974b4.js',
            ],
            'css' => [
                '/build/app.36a03b21.css',
            ],
        ],
    ],
],

]];
