<?php

namespace ContainerSkLGdUg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ArticleService' shared autowired service.
     *
     * @return \App\Services\ArticleService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ArticleService.php';

        return $container->privates['App\\Services\\ArticleService'] = new \App\Services\ArticleService(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['App\\Repository\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));
    }
}
